spring:
  application:
    # Never use '_' in application name
    # Use '-' instead
    # Otherwise gateway may not work correctly
    name: marketplace

  config:
    import:
      - file:../.env[.properties]
      - configserver:http://config_server:8888
